### ISSUE TITLE
[BUG] Pressing enter at the end of a checkbox line no longer creates a checkbox below it.

### ISSUE THREAD

**Issue by psychsatani** [vslinko/obsidian-outliner#153]
**Describe the bug**
Pressing enter at the end of a checkbox no longer creates a checkbox below it.

**To Reproduce**
Steps to reproduce the behavior (also see screen recording attached):
1. Press - [ ] and type something. 
2. Press enter
3. You get a bullet instead of a checkbox

**Expected behavior**
Pressing enter at the end of a line with a checkbox should create a checkbox below it.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Obsidian Version: 0.12.4

**Additional context**
I disabled all plugins, the issue disappeared. It reappears only with outliner plugin enabled. 

https://user-images.githubusercontent.com/78266798/120009958-33fed500-bffa-11eb-90cb-bfaeb569a20d.mov

**Comment by oldjove** [comment]
I also experienced this using 0.12.4 on Windows. Also used a process of elimination and found that this plugin was causing it.

**Comment by heliostatic** [comment]
Reproduced this issue, specifically it is the "Enhance the Enter key" setting.

https://user-images.githubusercontent.com/70898/120261790-a116a280-c266-11eb-9271-108d992bfe2c.mp4

**Comment by psychsatani** [comment]
Thank you 

> Reproduced this issue, specifically it is the "Enhance the Enter key" setting.
> 
>  CleanShot.2021-05-31.at.23.16.48.mp4

**Comment by vslinko** [comment]
Thank you all for your contributions. Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.2

**Comment by danielskowronski** [comment]
The issue is still there for custom checkbox states (as introduced for example by TaskCollector). See https://github.com/ebullient/obsidian-task-collector/issues/60 for more details, but it boils down to supporting task elements that have `data-task` property other than ` ` and `x` - for example `!` or `-`.

DOM tree for simple note having multiple different task states:
```html
<div class="cm-contentContainer">
  <div spellcheck="false" autocorrect="on" autocapitalize="on" translate="no" contenteditable="true" class="cm-content" style="tab-size: 4; padding-bottom: 474px;" role="textbox" aria-multiline="true">
    <div class="cm-line">task states demo</div>
    <div class="HyperMD-list-line HyperMD-list-line-1 HyperMD-task-line cm-line" data-task=" " style="text-indent:-25px;padding-left:29px">
      <div class="cm-fold-indicator" contenteditable="false">
        <div class="collapse-indicator collapse-icon">
          <svg viewBox="0 0 100 100" class="right-triangle" width="8" height="8">
            <path fill="currentColor" stroke="currentColor" d="M94.9,20.8c-1.4-2.5-4.1-4.1-7.1-4.1H12.2c-3,0-5.7,1.6-7.1,4.1c-1.3,2.4-1.2,5.2,0.2,7.6L43.1,88c1.5,2.3,4,3.7,6.9,3.7 s5.4-1.4,6.9-3.7l37.8-59.6C96.1,26,96.2,23.2,94.9,20.8L94.9,20.8z"></path>
          </svg>
        </div>
      </div>
      <img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task=" "></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-1"> task with space</span>
    </div>
    <div class="HyperMD-list-line HyperMD-list-line-2 HyperMD-task-line cm-line" data-task=" " style="text-indent:-39px;padding-left:43px"><span class="cm-hmd-list-indent cm-hmd-list-indent-1"><span class="cm-indent">  </span></span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task=" "></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-2"> subtask with space</span></div>
    <div class="HyperMD-list-line HyperMD-list-line-1 HyperMD-task-line cm-line" data-task="x" style="text-indent:-25px;padding-left:29px">
      <div class="cm-fold-indicator" contenteditable="false">
        <div class="collapse-indicator collapse-icon">
          <svg viewBox="0 0 100 100" class="right-triangle" width="8" height="8">
            <path fill="currentColor" stroke="currentColor" d="M94.9,20.8c-1.4-2.5-4.1-4.1-7.1-4.1H12.2c-3,0-5.7,1.6-7.1,4.1c-1.3,2.4-1.2,5.2,0.2,7.6L43.1,88c1.5,2.3,4,3.7,6.9,3.7 s5.4-1.4,6.9-3.7l37.8-59.6C96.1,26,96.2,23.2,94.9,20.8L94.9,20.8z"></path>
          </svg>
        </div>
      </div>
      <img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task="x"></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-1"> task with </span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-inline-code cm-list-1" spellcheck="false">x</span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true">
    </div>
    <div class="HyperMD-list-line HyperMD-list-line-2 HyperMD-task-line cm-line" data-task=" " style="text-indent:-39px;padding-left:43px"><span class="cm-hmd-list-indent cm-hmd-list-indent-1"><span class="cm-indent">   </span></span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task=" "></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-2"> subtask with </span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-inline-code cm-list-2" spellcheck="false">x</span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"></div>
    <div class="HyperMD-list-line HyperMD-list-line-1 HyperMD-task-line cm-line" data-task="/" style="text-indent:-25px;padding-left:29px">
      <div class="cm-fold-indicator" contenteditable="false">
        <div class="collapse-indicator collapse-icon">
          <svg viewBox="0 0 100 100" class="right-triangle" width="8" height="8">
            <path fill="currentColor" stroke="currentColor" d="M94.9,20.8c-1.4-2.5-4.1-4.1-7.1-4.1H12.2c-3,0-5.7,1.6-7.1,4.1c-1.3,2.4-1.2,5.2,0.2,7.6L43.1,88c1.5,2.3,4,3.7,6.9,3.7 s5.4-1.4,6.9-3.7l37.8-59.6C96.1,26,96.2,23.2,94.9,20.8L94.9,20.8z"></path>
          </svg>
        </div>
      </div>
      <img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task="/"></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-1"> task with </span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-inline-code cm-list-1" spellcheck="false">/</span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true">
    </div>
    <div class="HyperMD-list-line HyperMD-list-line-2 HyperMD-task-line cm-line" data-task=" " style="text-indent:-39px;padding-left:43px"><span class="cm-hmd-list-indent cm-hmd-list-indent-1"><span class="cm-indent">    </span></span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task=" "></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-2"> subtask with </span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-inline-code cm-list-2" spellcheck="false">/</span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"></div>
    <div class="HyperMD-list-line HyperMD-list-line-1 HyperMD-task-line cm-line" data-task="-" style="text-indent:-25px;padding-left:29px">
      <div class="cm-fold-indicator" contenteditable="false">
        <div class="collapse-indicator collapse-icon">
          <svg viewBox="0 0 100 100" class="right-triangle" width="8" height="8">
            <path fill="currentColor" stroke="currentColor" d="M94.9,20.8c-1.4-2.5-4.1-4.1-7.1-4.1H12.2c-3,0-5.7,1.6-7.1,4.1c-1.3,2.4-1.2,5.2,0.2,7.6L43.1,88c1.5,2.3,4,3.7,6.9,3.7 s5.4-1.4,6.9-3.7l37.8-59.6C96.1,26,96.2,23.2,94.9,20.8L94.9,20.8z"></path>
          </svg>
        </div>
      </div>
      <img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task="-"></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-1"> task with </span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-inline-code cm-list-1" spellcheck="false">-</span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true">
    </div>
    <div class="HyperMD-list-line HyperMD-list-line-2 HyperMD-task-line cm-line" data-task="-" style="text-indent:-39px;padding-left:43px"><span class="cm-hmd-list-indent cm-hmd-list-indent-1"><span class="cm-indent">    </span></span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task="-"></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-2"> subtask with </span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-inline-code cm-list-2" spellcheck="false">-</span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"></div>
    <div class="HyperMD-list-line HyperMD-list-line-1 HyperMD-task-line cm-line" data-task="!" style="text-indent:-25px;padding-left:29px">
      <div class="cm-fold-indicator" contenteditable="false">
        <div class="collapse-indicator collapse-icon">
          <svg viewBox="0 0 100 100" class="right-triangle" width="8" height="8">
            <path fill="currentColor" stroke="currentColor" d="M94.9,20.8c-1.4-2.5-4.1-4.1-7.1-4.1H12.2c-3,0-5.7,1.6-7.1,4.1c-1.3,2.4-1.2,5.2,0.2,7.6L43.1,88c1.5,2.3,4,3.7,6.9,3.7 s5.4-1.4,6.9-3.7l37.8-59.6C96.1,26,96.2,23.2,94.9,20.8L94.9,20.8z"></path>
          </svg>
        </div>
      </div>
      <img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task="!"></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-1"> task with </span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-inline-code cm-list-1" spellcheck="false">!</span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true">
    </div>
    <div class="cm-active HyperMD-list-line HyperMD-list-line-2 HyperMD-task-line cm-line" data-task="!" style="text-indent:-39px;padding-left:43px"><span class="cm-hmd-list-indent cm-hmd-list-indent-1"><span class="cm-indent">  </span></span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><label class="task-list-label" contenteditable="false"><input class="task-list-item-checkbox" type="checkbox" data-task="!"></label><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-list-2"> subtask with </span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-inline-code cm-list-2" spellcheck="false">!</span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"></div>
  </div>
</div>
```

**Comment by vslinko** [comment]
@danielskowronski thank you for the feedback. should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.4.0
