### ISSUE TITLE
[FEAT] Japanese IME support to avoid key collisions

### ISSUE THREAD

**Issue by yo-goto** [vslinko/obsidian-outliner#154]
Hi, @vslinko. Thank you for developing this outliner plugin.

I have a feature request.
With Japanese IME, there are two kinds of key collision.

1. Enter key collision(string converting vs breaking a line)
2. Tab key collision(selecting predicated result in a popup window vs outliner indenting)

Typing Japanese sentences requires to convert characters and then confirm the input with IME. 
With Tab or Shift key to select predicated results in a popup window. With Enter key to determine the selection.

So, we have to push the Enter key twice to type a full sentence and break a line. 

In the current version, we can't type full sentences if `Enhance the Enter key` setting is enabled. The Enter key to convert strings collides with the Enter key to break line with IME. Besides, `Soft line break` is usable with `Enhance the Enter key` setting enabled. `Shift+Enter` just exits from the outline & can't do `Soft line break`.

To use `Soft line break` and natural indenting in outliner, please consider the feature to avoid these collisions with IME.

**To Reproduce**
1. Go to 'outliner setting tab'
2. Toggle `Enhance the Enter key` (setting is ON)
3. Type a Japanese sentence with IME

**Screenshots**

`Enhance the Enter key` setting is disabled. Can type a full sentence.
![settingDisabled](https://user-images.githubusercontent.com/50942816/120066786-13468600-c0b3-11eb-9e8a-93af644b917f.gif)

`Enhance the Enter key` setting is enabled. Can't type ↓
![settingEnabled](https://user-images.githubusercontent.com/50942816/120066788-15a8e000-c0b3-11eb-873d-f04b6bb33410.gif)

**Desktop (please complete the following information):**
 - OS: macOS BigSur 11.3
 - Obsidian Version: v0.12.4

**Additional context**
Related issue
- [Some buggy behavior in v1.12.1 · Discussion #151](https://github.com/vslinko/obsidian-outliner/discussions/151)
- [Japanese File Name Title copied to a note - Bug graveyard - Obsidian Forum](https://forum.obsidian.md/t/japanese-file-name-title-copied-to-a-note/8720?u=padaone)
- [IME Keyboard input collision - (Enter to Autocomplete vs Enter to Convert characters with IME) - Bug graveyard - Obsidian Forum](https://forum.obsidian.md/t/ime-keyboard-input-collision-enter-to-autocomplete-vs-enter-to-convert-characters-with-ime/10190)

**Comment by vslinko** [comment]
@yo-goto Thank you for your contribution! I reproduced the problem, but I don't know how to fix it. I' ll be thinking about it.

**Comment by yo-goto** [comment]
Ok, thanks. 
This issue in Advanced table and the implement in Kanban plugin may be helpful to solve it. 
Sorry, if I could understand how to implement, I would make a PR.

- [CJK improvement by listening keyboard input events · Issue #53 · tgrosinger/advanced-tables-obsidian](https://github.com/tgrosinger/advanced-tables-obsidian/issues/53)
- [Release 0.0.10 · mgmeyers/obsidian-kanban](https://github.com/mgmeyers/obsidian-kanban/releases/tag/0.0.10)

**Comment by vslinko** [comment]
@yo-goto Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.6

**Comment by yo-goto** [comment]
@vslinko Really thanks!
I've tested the latest release. `Enhanced the Enter key` seems working well. Now that I can do soft line break in Japanese.
But tab key collision still exists. If possible, please implement this one. 

Thanks.

**Comment by vslinko** [comment]
@yo-goto I can do that. Please open the new issue.
