### ISSUE TITLE
[BUG] Cannot move line up and down

### ISSUE THREAD

**Issue by Quorafind** [vslinko/obsidian-outliner#235]
**Describe the bug**

**To Reproduce**

Try markdown here:

```markdown
- [You should use forums rather than Slack/Discord to support developer community | Dan Moore!](https://www.mooreds.com/wordpress/archives/3451) #想法 
    - I run forums, I write forum software, I am pro forums.However I'd also add that it's important how to engage with a forum.
    My top tips : ( Error cause here )
    1. Financially fund a forum, but have the enthusiasts run it so it is arms length but official. If you run it, spin it up as a distinct thing so that future independence is possible and easy.
    2. Bless it fully, point everything you have at it and have your support staff answer questions, and allow your engineers to go deep on details where they can. Transparency wins, if you can't do it don't run a forum.
```

1. If the list contain text than indent and without no `-` or number.
2. It will cause the unusable result.
3. See error

**Expected behavior**
Can move list and sublist up and down.

**Desktop (please complete the following information):**
- version 0.2.0

**Comment by ajmz** [comment]
Yes, v2.0.0, Obsidian 0.13 Live Preview, still does not support Move list and sublists up/down.

**Comment by vslinko** [comment]
@Quorafind thank you for your feedback!
@ajmz plugin works, but there is a problem with markdown support.

Outliner plugin doesn't support the situation when the note line contains as many spaces as the list item. This is the reason why moving lines doesn't work.

As a workaround, you can add 4 spaces before the note line.

![Screen Recording 2021-12-27 at 11 34 43 mov](https://user-images.githubusercontent.com/205823/147452639-52af52ee-b0b1-4321-822c-567a236e8af8.gif)

**Comment by ajmz** [comment]
> Outliner plugin doesn't support the situation when the note line contains as many spaces as the list item. This is the reason why moving lines doesn't work.

Thanks.
I did what you said, but the problem remains, and not only the note line but also the line with "-".

**Comment by vslinko** [comment]
Hmm.

@ajmz Please enable "Debug mode" in the plugin settings, open Devtools by pressing <kbd>Command</kbd><kbd>Option</kbd><kbd>J</kbd> or <kbd>Control</kbd><kbd>Shift</kbd><kbd>J</kbd>, put your cursor on a header, press <kbd>Cmd</kbd><kbd>.</kbd>, copy output from Devtools here.

It also would be helpful if you could make a screen recording.

**Comment by freezoc** [comment]
I have the same issue, too. 
Outliner v2.0.5, Obsidian v0.13.14. Obsidian vault on both Windows and Mac, sync with iCloud. 
Works perfect on Mac, but functionality and hotkey setup on Windows is gone.
![1640654835(1)](https://user-images.githubusercontent.com/20424296/147518152-f379b33e-bef2-4d43-84b9-e14993cfcf81.png)

**Comment by mwufi** [comment]
![image](https://user-images.githubusercontent.com/30219253/147523750-3095651b-18ec-40c6-b769-778658d755f1.png)

lemme see if i can fix this, lol, i want this to work

**Comment by vslinko** [comment]
@freezoc could you please check the Outliner version on Windows machine? And ensure that “Use legacy editor” is disabled. Or try to reinstall the plug-in on Windows machine.

**Comment by freezoc** [comment]
@vslinko Outliner version is the same(v2.0.5) on both Windows and Mac machines. 
I've also tried reinstalling Outliner through the obsidian community and switching the legacy editor on and off. Still can't solve the problem.

**Comment by majicfanNew** [comment]
> 我也有同样的问题。大纲 v2.0.5， 黑曜石 v0.13.14.Windows和Mac上的黑曜石保险库，与iCloud同步。在Mac上工作完美，但Windows上的功能和热键设置已经消失。 ![1640654835(1)](https://user-images.githubusercontent.com/20424296/147518152-f379b33e-bef2-4d43-84b9-e14993cfcf81.png)

I have the same problem with you.i can not find the hotkeys of Outliner in hotkeys panel.

**Comment by majicfanNew** [comment]
@freezoc If you find out what the reason is, could you please let me know? I am also troubled by this problem. thank you

**Comment by majicfanNew** [comment]
debug mode

app.js:1 Obsidian Developer Console
app.js:1 Uncaught Error: Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Invalid language code provided: "zh-CN" is not a valid language code
Underlying stack: Error: Invalid language code provided: "zh-CN" is not a valid language code
    at electron/js2c/browser_init.js:221:8665
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)

    at electron/js2c/browser_init.js:221:8693
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)
ObsidianOutlinerPlugin.ts:35 Loading obsidian-outliner
tslib.es6.js:74 Uncaught (in promise) Error: Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Invalid language code provided: "zh-CN" is not a valid language code
Underlying stack: Error: Invalid language code provided: "zh-CN" is not a valid language code
    at electron/js2c/browser_init.js:221:8665
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)

    at electron/js2c/browser_init.js:221:8693
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)
ObsidianZoomPlugin.ts:27 Loading obsidian-zoom
tslib.es6.js:74 Uncaught (in promise) Error: Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Invalid language code provided: "zh-CN" is not a valid language code
Underlying stack: Error: Invalid language code provided: "zh-CN" is not a valid language code
    at electron/js2c/browser_init.js:221:8665
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)

    at electron/js2c/browser_init.js:221:8693
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
    at Object.emit (events.js:315:20)

**Comment by majicfanNew** [comment]
i fixed the problem，you need turn off the spellcheck

**Comment by majicfanNew** [comment]
@ajmz @vslinko

**Comment by klancaster-unr** [comment]
I just found what I think is the issue. The Advanced Tables plugin uses the same default hotkeys for up and down. This was not a problem before as far as I can tell, but something changed recently. If you change the hotkey for up and down on either table or the outliner, outliner works again.

**Comment by ajmz** [comment]
> @ajmz @vslinko

I did it, but the issue remains.

**Comment by ajmz** [comment]
> i fixed the problem，you need turn off the spellcheck

I did it, but the issue remains.

**Comment by gityocode** [comment]
@vslinko I have this issue as well.  Have attempted the fixes tried by @freezoc and @ajmz but no success.

**Comment by xban12** [comment]
> i fixed the problem，you need turn off the spellcheck
I have the same problem with you and I also tryed diabling the spell checking, and the issue remain.
@vslinko

**Comment by ajmz** [comment]
Obsidian Release v0.13.19, the issue is solved.

**Comment by cvjxendra** [comment]
For me, the issue remains. Obsidian v0.13.19, Outliner 2.0.5

**Comment by matmilbury** [comment]
For me the 'Use legacy editor' option fixed the issue. For now 😬

**Comment by cvjxendra** [comment]
Debug mode give this error too:

`parseList Unable to parse list: expected some indent, got no indent`

**Comment by cvjxendra** [comment]
I think that I found a minimum reproducible outline with this bug. Please try open and move lines here:

[202201102019 bug outliner.md](https://github.com/vslinko/obsidian-outliner/files/7842528/202201102019.bug.outliner.md)
.

**Comment by vslinko** [comment]
@cvjxendra your use case should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.6

But your use case is different, and it is probably not related to other user problems.
I am closing this issue because it contains different problems, and some of them have already fixed.
If you still have a problem, please create a new issue with a detailed description.
