### ISSUE TITLE
[BUG] up arrow and CTRL-P (MAC editing key for up line) stop working in a list in Obsidian 18

### ISSUE THREAD

**Issue by jottos** [vslinko/obsidian-outliner#554]
**Describe the bug**
on version 1.8 of obsidian the up arrow and CTRL-P (MAC editing key for up line) stop working in a list unless you go to the plugin settings and tell it to "stick the cursor" never

**To Reproduce**

1. upgrade to version 18 of obsidian
2. if you have not changed the default settings stick the cursor will be set to "outside of bullets and checklists" 
3. CTRL-P and Up Arrow will no longer work within a list
4. change setting to "Never" and they will work again

**Expected behavior**
Up Arrow and CTRL-P navigate up the list (as they did prior to version 1.8

**Screenshots**
this is the default setting which was fine up through Obsidian V1.7, this now needs to be set to "Never" or up navigation does not work
![Image](https://github.com/user-attachments/assets/418dc240-cab9-4dde-b20a-073e6d9f1972)

**Environment (please complete the following information):**
 - OS: MAC
 - Obsidian Version: 1.8.4
 - Plugin Version: latest

**Additional context**
None

**Comment by zedtools** [comment]
I'm seeing this too on macOS.

**Comment by vslinko** [comment]
Thank you for the feedback. Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/4.8.2

**Comment by Cateroo** [comment]
Sorry, but I'm still having this issue on macOS - using version 4.9.0 and it is exactly as jottos described earlier. 
I'm using Obsidian v 1.9.12. 

Thanks
